services:
  - type: web
    name: pubmed-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11